version: '3'

services:
  bitwarden:
    # Standard Bitwarden is very resource-heavy and cannot run on micro cloud instances
    # Bitwarden Rust is a Rust (mostly) feature-complete implementation of Bitwarden
    # https://github.com/dani-garcia/bitwarden_rs
    image: bitwardenrs/server:alpine
    restart: always
    container_name: bitwarden
    volumes:
    - ./bitwarden:/data
    environment:
    - LOG_FILE=/data/bitwarden.log
    - WEBSOCKET_ENABLED=true            # required for websockets
    - SHOW_PASSWORD_HINT=false
    - DOMAIN=https://${DOMAIN}          # DOMAIN is set in .env but doesn't have protocol prefix
    - SMTP_FROM_NAME=Bitwarden (${DOMAIN})
    - IP_HEADER=X-Forwarded-For
    - ADMIN_TOKEN                       # Value-less variables are set in .env
    - SIGNUPS_ALLOWED
    - SMTP_HOST
    - SMTP_FROM
    - SMTP_PORT
    - SMTP_SSL
    - SMTP_USERNAME
    - SMTP_PASSWORD
 
  proxy:
    image: jlesage/nginx-proxy-manager
    build: .
    ports:
      - "81:8181"
      - "80:8080"
      - "443:4443"
    volumes:
      - "./nginx-proxy-manager:/config:rw"
